name: cs598-psl-env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3
  - jupyter 
  - configparser
  - requests
  - pandas 
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - seaborn
  # - pip:
  #   - ISLP
