name: cs598-psl-env-proj-1
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.12
  - pandas=2.1.1
  - scipy=1.11.3
  - numpy=1.26.0
  - scikit-learn=1.3.1
  - tqdm
  # - sklearn=1.3.1
  # - xgboost=2.0.0 
  # - lightGBM=4.1.0
  # - Catboost=1.2.2
  # - category_encoders=2.6.2
  # - feature_engine.outliers=1.6.2
  # - glmnet_python=0.1.0b2
  # - rpy2=3.5.14
  #- warnings (build-in)  
  # - pip
  # - jupyter 
  # - configparser
  # - requests
  # - pandas 
  # - numpy
  # - scipy
  # - matplotlib
  # - scikit-learn
  # - seaborn
  # - statsmodels
  # - tqdm
  # - threadpoolctl=3
  # - pip:
  #   - ISLP
  #   - scikit-fda
  #   - scikit-misc
